networks:
  backend:
    driver: bridge

volumes:
  postgresql:
    driver: local

services:
  postgresql:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=multitranslator
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5555:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    env_file:
      - .env
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/multitranslator
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  app:
    build:
      context: .
    depends_on:
      - postgresql
      - liquibase-migrations
    env_file:
      - .env
    networks:
      - backend
    environment:
      - HOST=postgres:5432
      - POSTGRES_DB=multitranslator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8080:8080'